-- CARDS_DECK definition

CREATE TABLE CARDS_DECK (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	NAME TEXT(200) NOT NULL,
	DESCRIPTION TEXT
, SUIT TEXT(200) DEFAULT NOT_ASSIGNED NOT NULL, PRINCIPALITY TEXT(200) DEFAULT NONE NOT NULL, ARCANA TEXT(200) DEFAULT NOT_ASSIGNED NOT NULL, IMAGE BLOB, IMAGEBACK BLOB);

CREATE UNIQUE INDEX CARDS_DECK_NAME_IDX ON CARDS_DECK (NAME);
